localization_distance:
  topics:
    - "/base_pose_ground_truth"
    - "/tf"
wait_for_topics: []                                   # Names of the topics to wait for before beginning the test
wait_for_services: []                                 # Names of the services to wait for before beginning the test
additional_parameters:                                # Name and value of additional parameter which will be included in every recording test file
  "/use_sim_time": true
  "/bag": /home/pfs/atf_bags/2018-03-07-16-10-10.bag
additional_arguments: []                              # Name and value of additional arguments which will be included in every recording test file
